### ISSUE TITLE
[QUESTION] Does the tool recompose .EXT file from .PNG?

### ISSUE THREAD

**Issue by Antonin-Carette-RedArtGames** [adventurebrew/boozook#14]
Hi,
Thanks for this tool!

From what I understood this tool can extract content from .STK / .TOT / ... and rebuild them.
But is it possible to reconstruct a .EXT file from the extracted graphics content (in .PNG)?

As an example, can I modify a graphics resource, reconstruct the .EXT from it, and repackage the .STK right after?
From the description of the tool it can, but I tried several times using the description provided from the README and it seems the tool does not reconstruct the .EXT file from the PNG.
But, to me, the workflow would be:
1. Extract the content of the game, (`boozook.archive`)
2. Extract the graphics from the extracted content (to PNG), (`boozook.graphics`)
3. Modify the PNG, 
4. Compress the PNG to an EXT file, (`boozook.graphics -r` **?**)
5. Place the new EXT file in the resource folder, and repackage the game (`boozook.archive -r` **?**).

Looking at the source code, in `graphics.compose`, you are looking from the PNG but it does not work at all for me.

Also, I have an issue reconstructing the overall game:

```sh
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Antonin\Devel\Engines\boozook\src\boozook\archive.py", line 223, in <module>
    main(args.directory, args.rebuild, args.patterns)
  File "C:\Users\Antonin\Devel\Engines\boozook\src\boozook\archive.py", line 214, in main
    extract_archive(game, extract_dir, patterns=patterns)
  File "C:\Users\Antonin\Devel\Engines\boozook\src\boozook\archive.py", line 144, in extract_archive
    for pattern, entry in game.search(patterns):
                          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Antonin\Devel\Engines\boozook\src\boozook\archive.py", line 42, in game_search
    with stk.open(archive_path) as archive:
         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Antonin\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\Antonin\AppData\Local\pypoetry\Cache\virtualenvs\boozook-LlCt3XiS-py3.12\Lib\site-packages\pakal\archive.py", line 279, in opener
    with archive_type(*args, **kwargs) as inst:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Antonin\AppData\Local\pypoetry\Cache\virtualenvs\boozook-LlCt3XiS-py3.12\Lib\site-packages\pakal\archive.py", line 200, in __init__
    self._stream = self._io.open(file, 'rb')
    
PermissionError: [Errno 13] Permission denied: '...\\extracted\\INTRO.STK'
```

I pointed it directly to the `extracted` folder that contains all previously extracted files & directories:
```sh
python -m boozook.archive D:\mygame # works
python -m boozook.archive D:\extracted -r # fails
```

The directory `extracted` contains the list of all extracted directories from the previous command, as listed here:
```sh
d-----         9/10/2024  EXT.STK
d-----         9/10/2024  IMD.ITK
d-----         9/10/2024  INTRO.STK
d-----         9/10/2024  TOT.STK
```

Thanks in advance!

**Comment by BJNFNE** [comment]
Hi, when i wrote the README the commands are maybe outdated compared to the latest codebase of boozook i Check later

**Comment by Antonin-Carette-RedArtGames** [comment]
Thanks @BJNFNE ,

I modified my post in order to reflect my workflow.
I hope this will make the things clearer.

**Comment by BJNFNE** [comment]
@Antonin-Carette-RedArtGames can you may retry under poetry? Are you confident with poetry if no I can help

**Comment by Antonin-Carette-RedArtGames** [comment]
I already use boozook in its poetry environment actually

**Comment by BJNFNE** [comment]
Can you provide me your Python and poetry version?

**Comment by Antonin-Carette-RedArtGames** [comment]
No problem, sorry for not having mentioned that before:

```sh
(boozook-py3.12) PS D:\boozook\src> python --version
Python 3.12.6
(boozook-py3.12) PS D:\boozook\src> poetry --version
Poetry (version 1.8.3)
```

**Comment by BJNFNE** [comment]
So you are in the src folder, you have to go to the root directory of boozook. Can you may try this?

**Comment by Antonin-Carette-RedArtGames** [comment]
The issue seems that the "repackager" tries to open `INTRO.STK` as a file (using `rb`).
So I don't really know if I am using the right way to rebuild the game.

The README mentions that the `rebuild` path should be the `extracted` directory (which contains the subdirectories), is it still the case?

Do I need to call `boozook.archive -r` on the directory that contains `EXT.STK`, `INTRO.STK`, ...
or only on `EXT.STK` for example?

**Comment by Antonin-Carette-RedArtGames** [comment]
> So you are in the src folder, you have to go to the root directory of boozook. Can you may try this?

Good point, but same issue unfortunately.

**Comment by BJNFNE** [comment]
Can you may also try the interactive mode with: 
python -m boozook.runner --experimental PATH
to run boozook in interactive mode

**Comment by BJNFNE** [comment]
> Can you may also try the interactive mode with: 
> python -m boozook.runner --experimental PATH
> to run boozook in interactive mode

Replace PATH to point to the directory of the Game data archives

**Comment by Antonin-Carette-RedArtGames** [comment]
Oh wow, nice interactive mode! 👏 

So, I replace `PATH` to the game data archives, got it, but how does it know which "graphics" resource (PNG) to replace please? 
Do I have to provide an "entry" directory to get the PNG to inject?

**Comment by BJNFNE** [comment]
You just modifiy the Picture or replace it with an new image and you have to name it as the original was and then you can recompress the archives

**Comment by Antonin-Carette-RedArtGames** [comment]
Thanks, it works with the interactive mode 👍 

If you want I can document all of this in the README and create a PR for this.
However I will have to find a bit of time, so I can't guarantee I could submit it in the next few days.

Thanks again!

**Comment by BLooperZ** [comment]
Hi, thank you both :)
Glad to hear you found the tool and the interactive mode useful.

For completion sake, I would like to note regarding usage for the non-interactive mode as well:
the path parameter always refer to the original game directory (the directory with the stk files)
both for extract and rebuild, so it didn't work when providing the extracted directory
for example, for extracting and injecting graphics
(when using activated poetry shell `boozook` is the same as `python -m boozook.runner`)
```boozook --graphics D:\mygame```
then for injecting
```boozook --graphics D:\mygame -r```
please note the path stayed the same path in both commands... this is the same for archives(`--archive`), texts(`--texts`), fonts(`--fonts`) etc.

hope it helps
also thanks for offering to document the usage and opening PR, it would be very helpful, much appreciated

**Comment by BJNFNE** [comment]
Hi @Antonin-Carette-RedArtGames how you are doing? Is there already some Progress on working on the README? I can also help you if you don't mind.

**Comment by Antonin-Carette-RedArtGames** [comment]
Hi @BJNFNE ,

Sorry I am a bit busy right now but I will work on it tomorrow, and submit the PR for this weekend.
Cheers!

**Comment by Antonin-Carette-RedArtGames** [comment]
Hi, I am deeply sorry but I did not get the time to do it last week.
I will have time this Wednesday and try submit the PR the same day, sorry again.

**Comment by BJNFNE** [comment]
No problem take your time!

**Comment by Antonin-Carette-RedArtGames** [comment]
Maybe this issue should be closed now, as the original problem has been fixed.

**Comment by BJNFNE** [comment]
Closing then
